
spring.resources.static-locations:
- file:src/main/resources/public/
- classpath:/public/

shell:
  main:
#    path: ../work/kzen-launcher/kzen-launcher-jvm-0.5.1-SNAPSHOT.jar
    path: ../work/kzen-launcher/kzen-launcher-jvm-0.6.0.jar
#    download: file:///home/ao/IdeaProjects/kzen-launcher/kzen-launcher-jvm/build/libs/kzen-launcher-jvm-0.5.1-SNAPSHOT.jar
#    download: file:///C:/~/proj/kzen-launcher/kzen-launcher-jvm/build/libs/kzen-launcher-jvm-0.3.0.jar
    download: https://github.com/alexoooo/kzen-launcher/releases/download/v0.6.0/kzen-launcher-jvm-0.6.0.jar
