
spring.resources.static-locations:
- file:src/main/resources/public/
- classpath:/public/

shell:
  main:
#    path: work/kzen-launcher/server-0.0.1.jar
#    path: work/kzen-launcher/kzen-launcher-jvm-0.0.6.jar
#    path: work/kzen-launcher/kzen-launcher-jvm-0.3.0.jar
#    path: ../work/kzen-launcher/kzen-launcher-jvm-0.0.2-SNAPSHOT.jar
    path: ../work/kzen-launcher/kzen-launcher-jvm-0.3.1.jar
#    download: https://github.com/alexoooo/kzen-launcher/releases/download/v0.0.1/server-0.0.1.jar
#    download: file:///home/ao/proj/kzen-launcher/kzen-launcher-jvm/build/libs/kzen-launcher-jvm-0.0.4.jar
#    download: file:///home/ao/IdeaProjects/kzen-launcher/kzen-launcher-jvm/build/libs/kzen-launcher-jvm-0.3.0.jar
#    download: file:///C:/~/proj/kzen-launcher/kzen-launcher-jvm/build/libs/kzen-launcher-jvm-0.3.0.jar
#    download: https://github.com/alexoooo/kzen-launcher/releases/download/v0.0.6/kzen-launcher-jvm-0.0.6.jar
    download: https://github.com/alexoooo/kzen-launcher/releases/download/v0.3.1/kzen-launcher-jvm-0.3.1.jar
