
spring.resources.static-locations:
  - file:src/main/resources/public/
  - classpath:/public/

shell:
  main:
    path: ../work/kzen-launcher/kzen-launcher-jvm-0.25.0.jar
#    download: https://github.com/alexoooo/kzen-launcher/releases/download/v0.25.0/kzen-launcher-jvm-0.25.0.jar
#    download: file:///home/ao/IdeaProjects/kzen-launcher/kzen-launcher-jvm/build/libs/kzen-launcher-jvm-0.24.0.jar
    download: file:///C:/Users/ao/IdeaProjects/kzen-launcher/kzen-launcher-jvm/build/libs/kzen-launcher-jvm-0.25.1-SNAPSHOT.zip
